name: rlenv
dependencies:
  - python==3.10
  - pip
  - pip:
    - torch
    - numpy==1.26.4
    - tensorboardX
    - tensorflow
    - seaborn
    - pettingzoo
    - matplotlib
    - stable_baselines3
    - git+https://github.com/Farama-Foundation/d4rl@master#egg=d4rl
    - patchelf
    - cython<3
    - wandb


